version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: pelican
    volumes:
      - ./output:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80