from pelican.paginator import PaginationRule
from pelican.utils import SafeDatetime

x = {
    "settings": {
        "PATH": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/content",
        "ARTICLE_PATHS": [""],
        "ARTICLE_EXCLUDES": ["pages"],
        "PAGE_PATHS": ["pages"],
        "PAGE_EXCLUDES": [""],
        "THEME": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/themes/jan-blog",
        "OUTPUT_PATH": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/output",
        "READERS": {},
        "STATIC_PATHS": ["images"],
        "STATIC_EXCLUDES": [],
        "STATIC_EXCLUDE_SOURCES": True,
        "THEME_STATIC_DIR": "theme",
        "THEME_STATIC_PATHS": ["static"],
        "FEED_ALL_ATOM": None,
        "CATEGORY_FEED_ATOM": None,
        "AUTHOR_FEED_ATOM": None,
        "AUTHOR_FEED_RSS": None,
        "TRANSLATION_FEED_ATOM": None,
        "FEED_MAX_ITEMS": "",
        "RSS_FEED_SUMMARY_ONLY": True,
        "SITEURL": "localhost",
        "SITENAME": "Johnnyho Blog",
        "DISPLAY_PAGES_ON_MENU": True,
        "DISPLAY_CATEGORIES_ON_MENU": True,
        "DOCUTILS_SETTINGS": {},
        "OUTPUT_SOURCES": False,
        "OUTPUT_SOURCES_EXTENSION": ".text",
        "USE_FOLDER_AS_CATEGORY": True,
        "DEFAULT_CATEGORY": "other",
        "WITH_FUTURE_DATES": True,
        "CSS_FILE": "main.css",
        "NEWEST_FIRST_ARCHIVES": True,
        "REVERSE_CATEGORY_ORDER": False,
        "DELETE_OUTPUT_DIRECTORY": False,
        "OUTPUT_RETENTION": [],
        "INDEX_SAVE_AS": "index.html",
        "ARTICLE_URL": "{date:%Y}/{date:%M}/{date:%d}/{slug}.html",
        "ARTICLE_SAVE_AS": "{date:%Y}/{date:%M}/{date:%d}/{slug}.html",
        "ARTICLE_ORDER_BY": "reversed-date",
        "ARTICLE_LANG_URL": "{slug}-{lang}.html",
        "ARTICLE_LANG_SAVE_AS": "{slug}-{lang}.html",
        "DRAFT_URL": "drafts/{slug}.html",
        "DRAFT_SAVE_AS": "drafts/{slug}.html",
        "DRAFT_LANG_URL": "drafts/{slug}-{lang}.html",
        "DRAFT_LANG_SAVE_AS": "drafts/{slug}-{lang}.html",
        "PAGE_URL": "pages/{slug}.html",
        "PAGE_SAVE_AS": "pages/{slug}.html",
        "PAGE_ORDER_BY": "basename",
        "PAGE_LANG_URL": "pages/{slug}-{lang}.html",
        "PAGE_LANG_SAVE_AS": "pages/{slug}-{lang}.html",
        "DRAFT_PAGE_URL": "drafts/pages/{slug}.html",
        "DRAFT_PAGE_SAVE_AS": "drafts/pages/{slug}.html",
        "DRAFT_PAGE_LANG_URL": "drafts/pages/{slug}-{lang}.html",
        "DRAFT_PAGE_LANG_SAVE_AS": "drafts/pages/{slug}-{lang}.html",
        "STATIC_URL": "{path}",
        "STATIC_SAVE_AS": "{path}",
        "STATIC_CREATE_LINKS": False,
        "STATIC_CHECK_IF_MODIFIED": False,
        "CATEGORY_URL": "category/{slug}.html",
        "CATEGORY_SAVE_AS": "category/{slug}.html",
        "TAG_URL": "tag/{slug}.html",
        "TAG_SAVE_AS": "tag/{slug}.html",
        "AUTHOR_URL": "author/{slug}.html",
        "AUTHOR_SAVE_AS": "author/{slug}.html",
        "PAGINATION_PATTERNS": [
            PaginationRule(
                min_page=1, URL="{name}{extension}", SAVE_AS="{name}{extension}"
            ),
            PaginationRule(
                min_page=2,
                URL="{name}{number}{extension}",
                SAVE_AS="{name}{number}{extension}",
            ),
        ],
        "YEAR_ARCHIVE_URL": "",
        "YEAR_ARCHIVE_SAVE_AS": "",
        "MONTH_ARCHIVE_URL": "",
        "MONTH_ARCHIVE_SAVE_AS": "",
        "DAY_ARCHIVE_URL": "",
        "DAY_ARCHIVE_SAVE_AS": "",
        "RELATIVE_URLS": True,
        "DEFAULT_LANG": "en",
        "ARTICLE_TRANSLATION_ID": "slug",
        "PAGE_TRANSLATION_ID": "slug",
        "DIRECT_TEMPLATES": ["index", "tags", "categories", "authors", "archives"],
        "THEME_TEMPLATES_OVERRIDES": [],
        "PAGINATED_TEMPLATES": {
            "index": None,
            "tag": None,
            "category": None,
            "author": None,
        },
        "PELICAN_CLASS": "pelican.Pelican",
        "DEFAULT_DATE_FORMAT": "%d",
        "DATE_FORMATS": {},
        "MARKDOWN": {
            "extension_configs": {
                "markdown.extensions.codehilite": {"css_class": "highlight"},
                "markdown.extensions.extra": {},
                "markdown.extensions.meta": {},
            },
            "output_format": "html5",
        },
        "JINJA_FILTERS": {},
        "JINJA_ENVIRONMENT": {
            "extensions": ["jinja2.ext.i18n"],
            "lstrip_blocks": True,
            "trim_blocks": True,
        },
        "LOG_FILTER": [],
        "LOCALE": [""],
        "DEFAULT_PAGINATION": False,
        "DEFAULT_ORPHANS": 0,
        "DEFAULT_METADATA": {},
        "FILENAME_METADATA": "(?P\\d{4}-\\d{2}-\\d{2}).*",
        "PATH_METADATA": "",
        "EXTRA_PATH_METADATA": {},
        "ARTICLE_PERMALINK_STRUCTURE": "",
        "TYPOGRIFY": False,
        "TYPOGRIFY_IGNORE_TAGS": [],
        "SUMMARY_MAX_LENGTH": 50,
        "PLUGIN_PATHS": [
            "/Users/jangazda/Dropbox/Coding/python/blog/pelican/plugins/pelican-plugins"
        ],
        "PLUGINS": ["assets"],
        "PYGMENTS_RST_OPTIONS": {},
        "TEMPLATE_PAGES": {},
        "TEMPLATE_EXTENSIONS": [".html"],
        "IGNORE_FILES": [".#*"],
        "SLUG_REGEX_SUBSTITUTIONS": [
            ("[^\\w\\s-]", ""),
            ("(?u)\\A\\s*", ""),
            ("(?u)\\s*\\Z", ""),
            ("[-\\s]+", "-"),
        ],
        "INTRASITE_LINK_REGEX": "[{|](?P.*?)[|}]",
        "SLUGIFY_SOURCE": "title",
        "CACHE_CONTENT": False,
        "CONTENT_CACHING_LAYER": "reader",
        "CACHE_PATH": "cache",
        "GZIP_CACHE": True,
        "CHECK_MODIFIED_METHOD": "mtime",
        "LOAD_CONTENT_CACHE": False,
        "WRITE_SELECTED": [],
        "FORMATTED_FIELDS": ["summary"],
        "PORT": 8000,
        "BIND": "",
        "ABSOLUTE_URL": "localhost",
        "AUTHOR": "Jan Gazda",
        "BOOTSTRAP_THEME": "slate",
        "CC_LICENSE": "CC-BY-SA-NC",
        "CREDITS": {"text": "Also a credit goes to …"},
        "DEFAULT_DATE": "fs",
        "DISABLE_SIDEBAR_TITLE_ICONS": True,
        "DISPLAY_CATEGORIES_ON_SIDEBAR": True,
        "DISPLAY_RECENT_POSTS_ON_SIDEBAR": True,
        "DISPLAY_TAGS_INLINE": True,
        "DISPLAY_TAGS_ON_SIDEBAR": True,
        "LINKS": (
            ("Pelican", "http://getpelican.com/"),
            ("Python.org", "http://python.org/"),
            ("Jinja2", "http://jinja.pocoo.org/"),
            ("You can modify those links in your config file", "#"),
        ),
        "PYGMENTS_STYLE": "monokai",
        "SITESUBTITLE": "Aneb bednicka s trubadury.",
        "SOCIAL": (
            ("https://gitlab.com/1oglop1", "gitlab"),
            ("https://github.com/1oglop1", "github"),
            ("https://linkedin.com/in/jangazda", "linkedin"),
        ),
        "STATIC_CDN": {
            "CSS": (
                'href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"',
                'href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"',
            ),
            "JS": (
                'src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"',
                'src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"',
                'src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"',
            ),
        },
        "TAGS_SAVE_AS": "tags.html",
        "TAGS_URL": "tags.html",
        "TAG_CLOUD_BADGE": True,
        "TIMEZONE": "Europe/Amsterdam",
        "DEBUG": False,
        "FEED_DOMAIN": "localhost",
    },
    "_content": "\n\nSo this is the magical content. asdasdasdasd\n",
    "_context": {
        "PATH": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/content",
        "ARTICLE_PATHS": [""],
        "ARTICLE_EXCLUDES": ["pages"],
        "PAGE_PATHS": ["pages"],
        "PAGE_EXCLUDES": [""],
        "THEME": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/themes/jan-blog",
        "OUTPUT_PATH": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/output",
        "READERS": {},
        "STATIC_PATHS": ["images"],
        "STATIC_EXCLUDES": [],
        "STATIC_EXCLUDE_SOURCES": True,
        "THEME_STATIC_DIR": "theme",
        "THEME_STATIC_PATHS": ["static"],
        "FEED_ALL_ATOM": None,
        "CATEGORY_FEED_ATOM": None,
        "AUTHOR_FEED_ATOM": None,
        "AUTHOR_FEED_RSS": None,
        "TRANSLATION_FEED_ATOM": None,
        "FEED_MAX_ITEMS": "",
        "RSS_FEED_SUMMARY_ONLY": True,
        "SITEURL": "localhost",
        "SITENAME": "Johnnyho Blog",
        "DISPLAY_PAGES_ON_MENU": True,
        "DISPLAY_CATEGORIES_ON_MENU": True,
        "DOCUTILS_SETTINGS": {},
        "OUTPUT_SOURCES": False,
        "OUTPUT_SOURCES_EXTENSION": ".text",
        "USE_FOLDER_AS_CATEGORY": True,
        "DEFAULT_CATEGORY": "other",
        "WITH_FUTURE_DATES": True,
        "CSS_FILE": "main.css",
        "NEWEST_FIRST_ARCHIVES": True,
        "REVERSE_CATEGORY_ORDER": False,
        "DELETE_OUTPUT_DIRECTORY": False,
        "OUTPUT_RETENTION": [],
        "INDEX_SAVE_AS": "index.html",
        "ARTICLE_URL": "{date:%Y}/{date:%M}/{date:%d}/{slug}.html",
        "ARTICLE_SAVE_AS": "{date:%Y}/{date:%M}/{date:%d}/{slug}.html",
        "ARTICLE_ORDER_BY": "reversed-date",
        "ARTICLE_LANG_URL": "{slug}-{lang}.html",
        "ARTICLE_LANG_SAVE_AS": "{slug}-{lang}.html",
        "DRAFT_URL": "drafts/{slug}.html",
        "DRAFT_SAVE_AS": "drafts/{slug}.html",
        "DRAFT_LANG_URL": "drafts/{slug}-{lang}.html",
        "DRAFT_LANG_SAVE_AS": "drafts/{slug}-{lang}.html",
        "PAGE_URL": "pages/{slug}.html",
        "PAGE_SAVE_AS": "pages/{slug}.html",
        "PAGE_ORDER_BY": "basename",
        "PAGE_LANG_URL": "pages/{slug}-{lang}.html",
        "PAGE_LANG_SAVE_AS": "pages/{slug}-{lang}.html",
        "DRAFT_PAGE_URL": "drafts/pages/{slug}.html",
        "DRAFT_PAGE_SAVE_AS": "drafts/pages/{slug}.html",
        "DRAFT_PAGE_LANG_URL": "drafts/pages/{slug}-{lang}.html",
        "DRAFT_PAGE_LANG_SAVE_AS": "drafts/pages/{slug}-{lang}.html",
        "STATIC_URL": "{path}",
        "STATIC_SAVE_AS": "{path}",
        "STATIC_CREATE_LINKS": False,
        "STATIC_CHECK_IF_MODIFIED": False,
        "CATEGORY_URL": "category/{slug}.html",
        "CATEGORY_SAVE_AS": "category/{slug}.html",
        "TAG_URL": "tag/{slug}.html",
        "TAG_SAVE_AS": "tag/{slug}.html",
        "AUTHOR_URL": "author/{slug}.html",
        "AUTHOR_SAVE_AS": "author/{slug}.html",
        "PAGINATION_PATTERNS": [
            PaginationRule(
                min_page=1, URL="{name}{extension}", SAVE_AS="{name}{extension}"
            ),
            PaginationRule(
                min_page=2,
                URL="{name}{number}{extension}",
                SAVE_AS="{name}{number}{extension}",
            ),
        ],
        "YEAR_ARCHIVE_URL": "",
        "YEAR_ARCHIVE_SAVE_AS": "",
        "MONTH_ARCHIVE_URL": "",
        "MONTH_ARCHIVE_SAVE_AS": "",
        "DAY_ARCHIVE_URL": "",
        "DAY_ARCHIVE_SAVE_AS": "",
        "RELATIVE_URLS": True,
        "DEFAULT_LANG": "en",
        "ARTICLE_TRANSLATION_ID": "slug",
        "PAGE_TRANSLATION_ID": "slug",
        "DIRECT_TEMPLATES": ["index", "tags", "categories", "authors", "archives"],
        "THEME_TEMPLATES_OVERRIDES": [],
        "PAGINATED_TEMPLATES": {
            "index": None,
            "tag": None,
            "category": None,
            "author": None,
        },
        "PELICAN_CLASS": "pelican.Pelican",
        "DEFAULT_DATE_FORMAT": "%d",
        "DATE_FORMATS": {},
        "MARKDOWN": {
            "extension_configs": {
                "markdown.extensions.codehilite": {"css_class": "highlight"},
                "markdown.extensions.extra": {},
                "markdown.extensions.meta": {},
            },
            "output_format": "html5",
        },
        "JINJA_FILTERS": {},
        "JINJA_ENVIRONMENT": {
            "extensions": ["jinja2.ext.i18n"],
            "lstrip_blocks": True,
            "trim_blocks": True,
        },
        "LOG_FILTER": [],
        "LOCALE": [""],
        "DEFAULT_PAGINATION": False,
        "DEFAULT_ORPHANS": 0,
        "DEFAULT_METADATA": {},
        "FILENAME_METADATA": "(?P\\d{4}-\\d{2}-\\d{2}).*",
        "PATH_METADATA": "",
        "EXTRA_PATH_METADATA": {},
        "ARTICLE_PERMALINK_STRUCTURE": "",
        "TYPOGRIFY": False,
        "TYPOGRIFY_IGNORE_TAGS": [],
        "SUMMARY_MAX_LENGTH": 50,
        "PLUGIN_PATHS": [
            "/Users/jangazda/Dropbox/Coding/python/blog/pelican/plugins/pelican-plugins"
        ],
        "PLUGINS": ["assets"],
        "PYGMENTS_RST_OPTIONS": {},
        "TEMPLATE_PAGES": {},
        "TEMPLATE_EXTENSIONS": [".html"],
        "IGNORE_FILES": [".#*"],
        "SLUG_REGEX_SUBSTITUTIONS": [
            ("[^\\w\\s-]", ""),
            ("(?u)\\A\\s*", ""),
            ("(?u)\\s*\\Z", ""),
            ("[-\\s]+", "-"),
        ],
        "INTRASITE_LINK_REGEX": "[{|](?P.*?)[|}]",
        "SLUGIFY_SOURCE": "title",
        "CACHE_CONTENT": False,
        "CONTENT_CACHING_LAYER": "reader",
        "CACHE_PATH": "cache",
        "GZIP_CACHE": True,
        "CHECK_MODIFIED_METHOD": "mtime",
        "LOAD_CONTENT_CACHE": False,
        "WRITE_SELECTED": [],
        "FORMATTED_FIELDS": ["summary"],
        "PORT": 8000,
        "BIND": "",
        "ABSOLUTE_URL": "localhost",
        "AUTHOR": "Jan Gazda",
        "BOOTSTRAP_THEME": "slate",
        "CC_LICENSE": "CC-BY-SA-NC",
        "CREDITS": {"text": "Also a credit goes to …"},
        "DEFAULT_DATE": "fs",
        "DISABLE_SIDEBAR_TITLE_ICONS": True,
        "DISPLAY_CATEGORIES_ON_SIDEBAR": True,
        "DISPLAY_RECENT_POSTS_ON_SIDEBAR": True,
        "DISPLAY_TAGS_INLINE": True,
        "DISPLAY_TAGS_ON_SIDEBAR": True,
        "LINKS": (
            ("Pelican", "http://getpelican.com/"),
            ("Python.org", "http://python.org/"),
            ("Jinja2", "http://jinja.pocoo.org/"),
            ("You can modify those links in your config file", "#"),
        ),
        "PYGMENTS_STYLE": "monokai",
        "SITESUBTITLE": "Aneb bednicka s trubadury.",
        "SOCIAL": (
            ("https://gitlab.com/1oglop1", "gitlab"),
            ("https://github.com/1oglop1", "github"),
            ("https://linkedin.com/in/jangazda", "linkedin"),
        ),
        "STATIC_CDN": {
            "CSS": (
                'href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"',
                'href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"',
            ),
            "JS": (
                'src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"',
                'src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"',
                'src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"',
            ),
        },
        "TAGS_SAVE_AS": "tags.html",
        "TAGS_URL": "tags.html",
        "TAG_CLOUD_BADGE": True,
        "TIMEZONE": "Europe/Amsterdam",
        "DEBUG": False,
        "FEED_DOMAIN": "localhost",
        "generated_content": {
            "hello.rst": "KOKOKO",
            "python/python.rst": "KOKOKO",
            "hello2.rst": "KOKOKO",
            "python/python-2.rst": "KOKOKO",
            "pages/about.rst": "KOKOKO",
        },
        "static_links": set(),
        "static_content": {},
        "localsiteurl": "../../..",
        "articles": "[,, , ]",
        "dates": "[,, , ]",
        "tags": "[(, [, ]), (, []), (, [, ]), (, [])]",
        "categories": "[(, []), (, []), (, [, ])]",
        "authors": "[( , [, , , ])]",
        "related_posts": [],
        "drafts": [],
        "pages": [],
        "hidden_pages": [],
        "draft_pages": [],
        "staticfiles": [],
    },
    "translations": [],
    "category": "KOKO",
    "date": SafeDatetime(2019, 1, 21, 7, 52, 40, 971658, tzinfo=None),
    "reader": "rst",
    "tags": "[, ]",
    "title": "Hello world",
    "metadata": {
        "category": "KOKO",
        "date": SafeDatetime(2019, 1, 21, 7, 52, 40, 971658),
        "reader": "rst",
        "tags": "[, ]",
        "summary": "Hello world 1.\n",
        "title": "Hello world",
    },
    "template": "article",
    "author": "KOKO",
    "authors": [],
    "in_default_lang": True,
    "lang": "en",
    "slug": "hello-world",
    "source_path": "/Users/jangazda/Dropbox/Coding/python/blog/pelican/content/hello.rst",
    "date_format": "%d",
    "locale_date": "21",
    "_status": "published",
}
